version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'advanced-node'
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
